/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as DirectivesRouteImport } from './routes/directives'
import { Route as ArchitectRouteImport } from './routes/architect'
import { Route as IndexRouteImport } from './routes/index'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectivesRoute = DirectivesRouteImport.update({
  id: '/directives',
  path: '/directives',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectRoute = ArchitectRouteImport.update({
  id: '/architect',
  path: '/architect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/directives': typeof DirectivesRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/recovery': typeof RecoveryRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/directives': typeof DirectivesRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/recovery': typeof RecoveryRoute
  '/status': typeof StatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/architect': typeof ArchitectRoute
  '/directives': typeof DirectivesRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/proof': typeof ProofRoute
  '/recovery': typeof RecoveryRoute
  '/status': typeof StatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/architect'
    | '/directives'
    | '/intake'
    | '/login'
    | '/proof'
    | '/recovery'
    | '/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/architect'
    | '/directives'
    | '/intake'
    | '/login'
    | '/proof'
    | '/recovery'
    | '/status'
  id:
    | '__root__'
    | '/'
    | '/architect'
    | '/directives'
    | '/intake'
    | '/login'
    | '/proof'
    | '/recovery'
    | '/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchitectRoute: typeof ArchitectRoute
  DirectivesRoute: typeof DirectivesRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  ProofRoute: typeof ProofRoute
  RecoveryRoute: typeof RecoveryRoute
  StatusRoute: typeof StatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directives': {
      id: '/directives'
      path: '/directives'
      fullPath: '/directives'
      preLoaderRoute: typeof DirectivesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architect': {
      id: '/architect'
      path: '/architect'
      fullPath: '/architect'
      preLoaderRoute: typeof ArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchitectRoute: ArchitectRoute,
  DirectivesRoute: DirectivesRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  ProofRoute: ProofRoute,
  RecoveryRoute: RecoveryRoute,
  StatusRoute: StatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
